#!/bin/sh

set -eu

title=""
stream=""
referrer=""
subtitle=""

for argument in "$@"; do
  case "$argument" in
    --force-media-title=*)
      title=${argument#--force-media-title=}
      ;;
    --referrer=*)
      referrer=${argument#--referrer=}
      ;;
    --sub-file=*)
      subtitle=${argument#--sub-file=}
      ;;
    http://*|https://*)
      stream=$argument
      ;;
  esac
done

[ -n "$stream" ] || exit 2

if [ -n "$title" ]; then
  printf 'ANICLI_TITLE\t%s\n' "$(printf '%s' "$title" | sed -E 's/ Episode [0-9]+$//')" >&2
fi

[ -n "$referrer" ] && printf 'ANICLI_STREAM_REFERRER\t%s\n' "$referrer" >&2
[ -n "$subtitle" ] && printf 'ANICLI_SUBTITLE_URL\t%s\n' "$subtitle" >&2
printf 'ANICLI_STREAM_URL\t%s\n' "$stream" >&2
